### ISSUE TITLE
Ошибка  при редактировании имени игрока, внесенного в команду

### ISSUE THREAD

**Issue by IceHarley** [IceHarley/nvl#16]
1. Создать игрока
2. Внести в состав команды
3. Выгрузить в airtable
4. Через список игроков войти в редактирование игрока
5. Внести новое имя

ОР: изменения сохранились
ФР: ошибка (node:3940) UnhandledPromiseRejectionWarning: Error: турниры не заданы. Ожидается массив
    at PlayersService.validate (file:///G:/projects/levin/nvl/players/playersService.js:137:35)
    at editPlayer (file:///G:/projects/levin/nvl/players/playersService.js:104:33)
    at SpinnerPlayersService.editPlayer (file:///G:/projects/levin/nvl/common/utils.js:65:12)
    at PlayerActions.selectPlayerAction (file:///G:/projects/levin/nvl/players/playerActions.js:32:44)
    at PlayerActions.applyPlayerAction (file:///G:/projects/levin/nvl/players/playerActions.js:10:55)
    at file:///G:/projects/levin/nvl/players/rosterMenu.js:103:45
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Аналогично, если в п.4 использовать меню состава команды

**Comment by IceHarley** [comment]
Аналогично при исключении такого игрока из команды
